### ISSUE TITLE
resolve to a path with no project.properties file for project 

### ISSUE THREAD

**Issue by ghost** [imhotep/MapKit#50]
/Users/alexander/Projects/android_sdk/tools/ant/build.xml:577: /Users/alexander/Projects/android_sdk/extras/google/google_play_services/libproject/google-play-services_lib/ resolve to a path with no project.properties file for project /Users/alexander/Projects/test_app/platforms/android

**Comment by HS-Singh** [comment]
I also have same issue. Is this issue resolved?
